"""Render the daily briefing as both markdown (for disk) and HTML (for email)."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date

from apewisdom_client import TickerData
from reddit_client import Post
from summarizer import Briefing


@dataclass
class ReportData:
    on_date: date
    posts_scanned: int
    tickers: list[TickerData]
    briefing: Briefing
    top_posts: list[Post]


def _sentiment_emoji(s: str) -> str:
    return {"bullish": "🟢", "bearish": "🔴", "mixed": "🟡", "neutral": "⚪"}.get(
        (s or "").lower(), "⚪"
    )


def _rank_change_md(t: TickerData) -> str:
    rc = t.rank_change
    if rc is None:
        return "new"
    if rc == 0:
        return "—"
    if rc > 0:
        return f"↑{rc}"
    return f"↓{-rc}"


def _rank_change_html(t: TickerData) -> str:
    rc = t.rank_change
    if rc is None:
        return '<span style="color:#888;">new</span>'
    if rc == 0:
        return '<span style="color:#888;">—</span>'
    if rc > 0:
        return f'<span style="color:#22863a;">▲{rc}</span>'
    return f'<span style="color:#b31d28;">▼{-rc}</span>'


def render_markdown(r: ReportData, top_n: int = 20) -> str:
    lines: list[str] = []
    lines.append(f"# WSB Morning Briefing — {r.on_date.isoformat()}")
    lines.append("")
    lines.append(
        f"Top WSB tickers from apewisdom.io + **{r.posts_scanned} top posts** "
        f"from r/wallstreetbets (last 24h)."
    )
    lines.append("")

    lines.append("## Market mood")
    lines.append(r.briefing.market_mood or "_no read_")
    lines.append("")

    lines.append("## Themes")
    if r.briefing.themes:
        for t in r.briefing.themes:
            lines.append(f"- {t}")
    else:
        lines.append("_no themes extracted_")
    lines.append("")

    lines.append(f"## Top {top_n} tickers")
    lines.append("")
    lines.append("| # | Δ | Ticker | Company | Industry | Mentions | Upvotes | Sentiment | WSB take |")
    lines.append("|---|---|--------|---------|----------|---------:|--------:|-----------|----------|")
    notes_by_symbol = {n.get("symbol", "").upper(): n for n in r.briefing.ticker_notes}
    for t in r.tickers[:top_n]:
        entry = notes_by_symbol.get(t.symbol, {})
        industry = entry.get("industry", "")
        sentiment = entry.get("sentiment", "")
        note = entry.get("note", "")
        sentiment_cell = f"{_sentiment_emoji(sentiment)} {sentiment}" if sentiment else ""
        lines.append(
            f"| {t.rank} | {_rank_change_md(t)} | **{t.symbol}** | {t.name} | "
            f"{industry} | {t.mentions} | {t.upvotes:,} | {sentiment_cell} | {note} |"
        )
    lines.append("")

    if r.top_posts:
        lines.append("## Top posts")
        for p in r.top_posts[:10]:
            lines.append(f"- **[{p.title}]({p.url})**")
            summary = r.briefing.post_summaries.get(p.id, "")
            if summary:
                lines.append(f"  {summary}")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by wsb-briefing. Ticker data: apewisdom.io. Not investment advice._")
    return "\n".join(lines)


_HTML_TEMPLATE = """<!DOCTYPE html>
<html><body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;max-width:820px;margin:0 auto;padding:20px;color:#1a1a1a;">
<h1 style="border-bottom:2px solid #ff4500;padding-bottom:8px;">WSB Morning Briefing</h1>
<p style="color:#666;">{date_str} &middot; Ticker data: apewisdom.io &middot; <b>{posts}</b> top posts scanned</p>

<h2>Market mood</h2>
<p style="background:#f6f7f8;padding:12px;border-left:4px solid #ff4500;">{mood}</p>

<h2>Themes</h2>
<ul>{themes_html}</ul>

<h2>Top {top_n} tickers</h2>
<table cellspacing="0" cellpadding="6" style="border-collapse:collapse;width:100%;font-size:14px;">
<thead><tr style="background:#f6f7f8;text-align:left;">
<th>#</th><th>Δ</th><th>Ticker</th><th>Company</th><th>Industry</th>
<th style="text-align:right;">Mentions</th><th style="text-align:right;">Upvotes</th>
<th>Sentiment</th><th>WSB take</th>
</tr></thead>
<tbody>
{ticker_rows}
</tbody>
</table>

{posts_section}

<hr style="margin-top:30px;border:none;border-top:1px solid #ddd;">
<p style="color:#888;font-size:12px;">Generated by wsb-briefing. Ticker data: apewisdom.io. Not investment advice.</p>
</body></html>
"""


def render_html(r: ReportData, top_n: int = 20) -> str:
    themes_html = "".join(f"<li>{_esc(t)}</li>" for t in r.briefing.themes) or "<li><i>no themes</i></li>"
    notes_by_symbol = {n.get("symbol", "").upper(): n for n in r.briefing.ticker_notes}
    rows: list[str] = []
    for t in r.tickers[:top_n]:
        entry = notes_by_symbol.get(t.symbol, {})
        industry = _esc(entry.get("industry", ""))
        sentiment = entry.get("sentiment", "")
        note = _esc(entry.get("note", ""))
        sentiment_html = (
            f"{_sentiment_emoji(sentiment)} {_esc(sentiment)}" if sentiment else ""
        )
        rows.append(
            f"<tr style='border-bottom:1px solid #eee;'>"
            f"<td>{t.rank}</td><td>{_rank_change_html(t)}</td>"
            f"<td><b>{t.symbol}</b></td>"
            f"<td>{_esc(t.name)}</td>"
            f"<td style='color:#666;'>{industry}</td>"
            f"<td style='text-align:right;'>{t.mentions}</td>"
            f"<td style='text-align:right;'>{t.upvotes:,}</td>"
            f"<td>{sentiment_html}</td>"
            f"<td>{note}</td></tr>"
        )

    if r.top_posts:
        post_items: list[str] = []
        for p in r.top_posts[:10]:
            summary = r.briefing.post_summaries.get(p.id, "")
            summary_html = (
                f'<div style="color:#444;margin-top:4px;font-size:13px;">{_esc(summary)}</div>'
                if summary else ""
            )
            post_items.append(
                f'<li style="margin-bottom:10px;">'
                f'<a href="{_esc(p.url)}" style="font-weight:600;color:#1a1a1a;">{_esc(p.title)}</a>'
                f"{summary_html}</li>"
            )
        posts_section = f"<h2>Top posts</h2><ul>{''.join(post_items)}</ul>"
    else:
        posts_section = ""

    return _HTML_TEMPLATE.format(
        date_str=r.on_date.strftime("%A, %B %d, %Y"),
        posts=r.posts_scanned,
        mood=_esc(r.briefing.market_mood or "no read"),
        themes_html=themes_html,
        top_n=top_n,
        ticker_rows="\n".join(rows),
        posts_section=posts_section,
    )


def _esc(s: str) -> str:
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
