"""Render the daily briefing as both markdown (for disk) and HTML (for email)."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date

from reddit_client import Post
from summarizer import Briefing
from ticker_extractor import TickerTally


@dataclass
class ReportData:
    on_date: date
    posts_scanned: int
    comments_scanned: int
    tickers: list[TickerTally]
    briefing: Briefing
    top_posts: list[Post]


def _sentiment_emoji(s: str) -> str:
    return {"bullish": "🟢", "bearish": "🔴", "mixed": "🟡", "neutral": "⚪"}.get(s, "⚪")


def render_markdown(r: ReportData, top_n: int = 20) -> str:
    lines: list[str] = []
    lines.append(f"# WSB Morning Briefing — {r.on_date.isoformat()}")
    lines.append("")
    lines.append(
        f"Scanned **{r.posts_scanned} posts** and **{r.comments_scanned} comments** "
        f"from r/wallstreetbets in the last 24h."
    )
    lines.append("")

    lines.append("## Market mood")
    lines.append(r.briefing.market_mood or "_no read_")
    lines.append("")

    lines.append("## Themes")
    if r.briefing.themes:
        for t in r.briefing.themes:
            lines.append(f"- {t}")
    else:
        lines.append("_no themes extracted_")
    lines.append("")

    lines.append(f"## Top {top_n} tickers")
    lines.append("")
    lines.append("| # | Ticker | Company | Industry | Mentions | Weighted ↑ | Sentiment | WSB take |")
    lines.append("|---|--------|---------|----------|----------|-----------:|-----------|----------|")
    notes_by_symbol = {
        n.get("symbol", "").upper(): n for n in r.briefing.ticker_notes
    }
    for i, t in enumerate(r.tickers[:top_n], start=1):
        entry = notes_by_symbol.get(t.symbol, {})
        name = entry.get("name", "")
        industry = entry.get("industry", "")
        note = entry.get("note", "")
        lines.append(
            f"| {i} | **{t.symbol}** | {name} | {industry} | {t.mention_count} | "
            f"{t.weighted_score:,} | {_sentiment_emoji(t.sentiment)} {t.sentiment} | {note} |"
        )
    lines.append("")

    lines.append("## Top posts")
    for p in r.top_posts[:10]:
        lines.append(f"- **[{p.title}]({p.url})** · {p.score}↑ · {p.num_comments}💬")
        summary = r.briefing.post_summaries.get(p.id, "")
        if summary:
            lines.append(f"  {summary}")
    lines.append("")
    lines.append("---")
    lines.append("_Generated by wsb-briefing. Not investment advice._")
    return "\n".join(lines)


_HTML_TEMPLATE = """<!DOCTYPE html>
<html><body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;max-width:760px;margin:0 auto;padding:20px;color:#1a1a1a;">
<h1 style="border-bottom:2px solid #ff4500;padding-bottom:8px;">WSB Morning Briefing</h1>
<p style="color:#666;">{date_str} &middot; Scanned <b>{posts}</b> posts &amp; <b>{comments}</b> comments</p>

<h2>Market mood</h2>
<p style="background:#f6f7f8;padding:12px;border-left:4px solid #ff4500;">{mood}</p>

<h2>Themes</h2>
<ul>{themes_html}</ul>

<h2>Top {top_n} tickers</h2>
<table cellspacing="0" cellpadding="6" style="border-collapse:collapse;width:100%;font-size:14px;">
<thead><tr style="background:#f6f7f8;text-align:left;">
<th>#</th><th>Ticker</th><th>Company</th><th>Industry</th><th style="text-align:right;">Mentions</th><th style="text-align:right;">Weighted ↑</th><th>Sentiment</th><th>WSB take</th>
</tr></thead>
<tbody>
{ticker_rows}
</tbody>
</table>

<h2>Top posts</h2>
<ul>{posts_html}</ul>

<hr style="margin-top:30px;border:none;border-top:1px solid #ddd;">
<p style="color:#888;font-size:12px;">Generated by wsb-briefing. Not investment advice.</p>
</body></html>
"""


def render_html(r: ReportData, top_n: int = 20) -> str:
    themes_html = "".join(f"<li>{_esc(t)}</li>" for t in r.briefing.themes) or "<li><i>no themes</i></li>"
    notes_by_symbol = {
        n.get("symbol", "").upper(): n for n in r.briefing.ticker_notes
    }
    rows: list[str] = []
    for i, t in enumerate(r.tickers[:top_n], start=1):
        entry = notes_by_symbol.get(t.symbol, {})
        name = _esc(entry.get("name", ""))
        industry = _esc(entry.get("industry", ""))
        note = _esc(entry.get("note", ""))
        rows.append(
            f"<tr style='border-bottom:1px solid #eee;'>"
            f"<td>{i}</td><td><b>{t.symbol}</b></td>"
            f"<td>{name}</td><td style='color:#666;'>{industry}</td>"
            f"<td style='text-align:right;'>{t.mention_count}</td>"
            f"<td style='text-align:right;'>{t.weighted_score:,}</td>"
            f"<td>{_sentiment_emoji(t.sentiment)} {t.sentiment}</td>"
            f"<td>{note}</td></tr>"
        )
    post_items: list[str] = []
    for p in r.top_posts[:10]:
        summary = r.briefing.post_summaries.get(p.id, "")
        summary_html = (
            f'<div style="color:#444;margin-top:4px;font-size:13px;">{_esc(summary)}</div>'
            if summary
            else ""
        )
        post_items.append(
            f'<li style="margin-bottom:10px;">'
            f'<a href="{_esc(p.url)}" style="font-weight:600;color:#1a1a1a;">{_esc(p.title)}</a> '
            f'<span style="color:#888;font-size:12px;">[{p.score}↑ · {p.num_comments}💬]</span>'
            f"{summary_html}"
            f"</li>"
        )
    posts_html = "".join(post_items)
    return _HTML_TEMPLATE.format(
        date_str=r.on_date.strftime("%A, %B %d, %Y"),
        posts=r.posts_scanned,
        comments=r.comments_scanned,
        mood=_esc(r.briefing.market_mood or "no read"),
        themes_html=themes_html,
        top_n=top_n,
        ticker_rows="\n".join(rows),
        posts_html=posts_html,
    )


def _esc(s: str) -> str:
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
